### ISSUE TITLE
python -m packagename.tests does not run

### ISSUE THREAD

**Issue by jrom99** [tpapastylianou/executable-python-package-template#13]
I'm not familiar with `unittest`, so I apologize in advance if I used it wrongly.

After downloading the repo and running:
```bash
python -m packagename.tests
```

I get:

```

Warning: No suitable VIRTUAL_ENV environmental variable detected.

In order to ensure consistency / reproducibility between runs, you might want to
consider always running this package from within a suitable python virtual
environment, containing the python package versions specified in the package's
requirements.txt file.

Press ENTER if you'd like to continue regardless (or Ctrl-C to abort)



__init__: Setting PKGROOT to /home/junior/Documents/Projetos/Python/self-contained-runnable-python-package-template/packagename
__init__: Setting INPUTS_PATH to /home/junior/Documents/Projetos/Python/self-contained-runnable-python-package-template/packagename/inputs
__init__: Setting OUTPUTS_PATH to /home/junior/Documents/Projetos/Python/self-contained-runnable-python-package-template/packagename/outputs
__init__: Setting MCMC_ENGINE to <class 'packagename.config.CONFIG.Stan'>
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/junior/Documents/Projetos/Python/self-contained-runnable-python-package-template/packagename/tests/__main__.py", line 41, in <module>
    if __name__ == '__main__': main()
  File "/home/junior/Documents/Projetos/Python/self-contained-runnable-python-package-template/packagename/tests/__main__.py", line 33, in main
    Tests  = unittest.defaultTestLoader.discover( start_dir = TestDir )
  File "/usr/lib64/python3.10/unittest/loader.py", line 306, in discover
    os.path.dirname((the_module.__file__)))
  File "/usr/lib64/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## System information:
$: python -VV
Python 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]

**Comment by tpapastylianou** [comment]
Hi @jrom99, thanks for reporting this!

I can confirm that the above code works for python v3.6.9, but fails for v3.8.10 on my machine with the exact same error.

So this seems to be some sort of regression bug introduced in later python versions, affecting the unittest module.

I will investigate and let you know :)

**Comment by tpapastylianou** [comment]
Thankfully the fix was as simple as adding an 'empty' `__init__.py` file in the packagename/tests directory :)

I have just made a commit (dbccce47a456f5eee0dc59229ced9b46f4190b4c) that does just this. See the comments inside the `packagename/tests/__init__.py` if you're interested for the explanation of what happened :)

Thanks again for reporting.

----

Update: I have also reported the main issue with unittest on the python bug tracker here: https://bugs.python.org/issue46635
